-- The full AEROBOOK schema: Better Auth's tables, then AEROBOOK's.
-- Generated by `npm run db:schema` against an empty database; `npm run db:migrate`
-- applies the same thing to DATABASE_URL.

create table "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null, "role" text, "banned" boolean, "banReason" text, "banExpires" timestamptz);

create table "session" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade, "impersonatedBy" text);

create table "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);

create table "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table "rateLimit" ("id" text not null primary key, "key" text not null unique, "count" integer not null, "lastRequest" bigint not null);

create index "session_userId_idx" on "session" ("userId");

create index "account_userId_idx" on "account" ("userId");

create index "verification_identifier_idx" on "verification" ("identifier");

create sequence if not exists app_record_seq;

create table if not exists app_record (
  collection text not null,
  id text not null,
  data jsonb,
  version integer not null default 1,
  seq bigint not null default nextval('app_record_seq'),
  updated_at timestamptz not null default now(),
  updated_by text,
  primary key (collection, id)
);
create index if not exists app_record_seq_idx on app_record (seq);

create table if not exists app_audit (
  id bigserial primary key,
  at timestamptz not null default now(),
  user_id text,
  user_name text,
  action text not null,
  collection text not null,
  record_id text not null,
  summary text not null default ''
);
create index if not exists app_audit_at_idx on app_audit (at desc);
-- What a record held before a change or deletion, so it can be put back.
alter table app_audit add column if not exists before jsonb;
create index if not exists app_audit_user_at_idx on app_audit (user_id, at);

-- Stored documents whose record went. The file is kept a while, so a
-- document deleted by mistake (or on purpose) can be restored, and removed
-- by the maintenance run only when no document record points at it.
create table if not exists app_file_trash (
  path text primary key,
  deleted_at timestamptz not null default now(),
  deleted_by text
);

-- Who has had today's email, so a repeated cron run sends nothing twice.
create table if not exists app_digest (
  user_id text not null,
  day date not null,
  sent_at timestamptz not null default now(),
  primary key (user_id, day)
);
