/**
 * The AEROBOOK brand: the owner's own signature, in two sizes.
 *
 * `Mark` is a tight crop of the signature's capital "A" — peak, the long
 * downstroke, the short one, the crossbar — reused as the logo (the app bar,
 * the splash screen) and, via the generated icon set, the home-screen icon.
 * `Signature` is the full hand, used only where there is room for it to
 * actually read as a signature: the quiet sign-off at the foot of the
 * dashboard.
 *
 * Both are CSS masks rather than inline SVG: the traced artwork lives in
 * `public/brand/*.svg` (regenerated by `npm run brand` from
 * `brand-source/signature.jpg`, never hand-edited), and a mask lets it take
 * the surrounding text colour and work in both themes from one asset.
 * Decorative — screen readers skip them and read the wordmark beside them
 * instead.
 */
export function Mark({ size = 22, className = '' }: { size?: number; className?: string }) {
  return (
    <span
      className={`mark ${className}`.trim()}
      aria-hidden="true"
      style={{ '--mark-width': `${size}px` } as React.CSSProperties}
    />
  );
}

function Signature({ width, className = '' }: { width?: number; className?: string }) {
  return (
    <span
      className={`signature ${className}`.trim()}
      aria-hidden="true"
      style={width ? ({ '--signature-width': `${width}px` } as React.CSSProperties) : undefined}
    />
  );
}

/** The quiet sign-off at the foot of the dashboard. */
export function Colophon() {
  return (
    <div className="colophon">
      <Signature />
      <span className="colophon__line">Aerobook</span>
    </div>
  );
}
