/**
 * The AEROBOOK brand: the winged emblem, the wordmark, and the owner's
 * signature.
 *
 * `Mark` is the gold emblem (`public/brand/mark.svg`, generated by
 * `npm run brand` — never hand-edited). It carries its own gold, so it is an
 * image rather than a mask and looks the same in both themes, as on the
 * brand sheet. `Lockup` pairs it with the spaced Montserrat wordmark, either
 * side by side (app bar, Settings) or stacked with the tagline (splash).
 * `Signature` is the full hand, used only where there is room for it to
 * actually read as a signature: the quiet sign-off at the foot of the
 * dashboard.
 *
 * The emblem and signature are decorative — screen readers skip them and
 * read the wordmark beside them instead.
 */
export const TAGLINE = 'Turnkey solutions for the sky';

export function Mark({ size = 36, className = '' }: { size?: number; className?: string }) {
  return (
    <img
      className={`mark ${className}`.trim()}
      src="/brand/mark.svg"
      alt=""
      aria-hidden="true"
      width={size}
      height={size / 3}
      draggable={false}
    />
  );
}

export function Lockup({ stacked = false, tagline = stacked }: { stacked?: boolean; tagline?: boolean }) {
  return (
    <span className={`lockup ${stacked ? 'lockup--stacked' : ''}`.trim()}>
      <Mark size={stacked ? 132 : 36} />
      <span className="lockup__text">
        <span className="lockup__wordmark">AEROBOOK</span>
        {tagline ? <span className="lockup__tagline">{TAGLINE}</span> : null}
      </span>
    </span>
  );
}

function Signature({ width, className = '' }: { width?: number; className?: string }) {
  return (
    <span
      className={`signature ${className}`.trim()}
      aria-hidden="true"
      style={width ? ({ '--signature-width': `${width}px` } as React.CSSProperties) : undefined}
    />
  );
}

/** The quiet sign-off at the foot of the dashboard. */
export function Colophon() {
  return (
    <div className="colophon">
      <Signature />
      <span className="colophon__line">Aerobook</span>
    </div>
  );
}
